# Nominal label verbalizations for the coarse-grained labels from the TeCla dataset, used for templateset 1.
verbalizations_templateset1_coarse_grained = {'Cultura': 'cultura', 
                                              'Política': 'política', 
                                              'Economia': 'economia', 
                                              'Societat': 'societat'}

# Adjective label verbalizations for the coarse-grained labels from the TeCla dataset, used for templateset 1.
verbalizations_templateset2_coarse_grained = {'Cultura': 'cultural', 
                                              'Política': 'polític', 
                                              'Economia': 'econòmic', 
                                              'Societat': 'social'}

# Nominal label verbalizations for the fine-grained labels from the TeCla dataset, used for templateset 1.
verbalizations_fine_grained = {'Llengua': 'llengua', 
                               'Infraestructures': 'infraestructures', 
                               'Arts': 'arts', 
                               'Parlament': 'Parlament', 
                               'Noves tecnologies': 'noves tecnologies', 
                               'Castells': 'castells', 
                               'Successos': 'successos', 
                               'Empresa': 'empresa', 
                               'Mobilitat': 'mobilitat', 
                               'Teatre': 'teatre', 
                               'Treball': 'treball', 
                               'Logística': 'logística', 
                               'Urbanisme': 'urbanisme', 
                               'Govern': 'Govern', 
                               'Entitats': 'entitats', 
                               'Finances': 'finances', 
                               'Govern espanyol': 'govern espanyol', 
                               'Trànsit': 'trànsit', 
                               'Indústria': 'indústria', 
                               'Esports': 'esports', 
                               'Exteriors': 'exteriors', 
                               'Medi ambient': 'medi ambient', 
                               'Habitatge': 'habitatge', 
                               'Salut': 'salut', 
                               'Equipaments i patrimoni': 'equipaments i patrimoni', 
                               'Recerca': 'recerca', 
                               'Cooperació': 'cooperació', 
                               'Innovació': 'innovació', 
                               'Agroalimentació': 'agroalimentació', 
                               'Policial': 'policial', 
                               'Serveis Socials': 'serveis socials', 
                               'Cinema': 'cinema', 
                               'Memòria històrica': 'memòria històrica', 
                               'Turisme': 'turisme', 
                               'Política municipal': 'política municipal', 
                               'Comerç': 'comerç', 
                               'Universitats': 'universitats', 
                               'Hisenda': 'hisenda', 
                               'Judicial': 'judicial', 
                               'Partits': 'partits', 
                               'Música': 'música', 
                               'Lletres': 'lletres', 
                               'Religió': 'religió', 
                               'Festa i cultura popular': 'festa i cultura popular', 
                               'Unió Europea': 'Unió Europea', 
                               'Moda': 'moda', 
                               'Moviments socials': 'moviments socials', 
                               'Comptes públics': 'comptes públics',
                               'Immigració': 'immigració', 
                               'Educació': 'educació', 
                               'Gastronomia': 'gastronomia', 
                               'Meteorologia': 'meteorologia', 
                               'Energia': 'energia'}